metadata:
  title: Custom Visuals Configuration
  description: Configuration for custom visuals integration
  created: 2025-08-14T17:30:06.181Z
visuals:
  architecture_diagram:
    filename: test-architecture.svg
    start: 60
    end: 90
    x: 100
    y: 200
    scale: 0.8
    opacity: 0.9
  api_flow_diagram:
    filename: api-flow-diagram.png
    start: 90
    end: 120
    x: 150
    y: 250
    scale: 0.7
    opacity: 0.9
  user_roles_chart:
    filename: user-roles-chart.png
    start: 40
    end: 60
    x: 200
    y: 150
    scale: 0.6
    opacity: 0.9
  value_proposition:
    filename: value-proposition.png
    start: 175
    end: 205
    x: 100
    y: 300
    scale: 0.8
    opacity: 0.9
overlays:
  logo:
    filename: logo.png
    start: 0
    end: 240
    x: w-150
    y: 50
    scale: 0.3
    opacity: 0.8
  watermark:
    filename: watermark.png
    start: 0
    end: 240
    x: 50
    y: h-100
    scale: 0.2
    opacity: 0.6
callouts:
  highlight_1:
    text: Key Feature
    start: 30
    end: 45
    x: 100
    y: 200
    color: yellow
    animation: fade_in
  highlight_2:
    text: Important Note
    start: 120
    end: 135
    x: 300
    y: 250
    color: red
    animation: slide_in
