# Graphics Configuration for Disaster Response Video
# This file allows you to customize graphics, overlays, and visual elements

metadata:
  title: "Disaster Response Dashboard - Graphics Configuration"
  version: "1.0"
  description: "Customize graphics, overlays, and visual elements for the video"

# Custom graphics configuration for each scene
scenes:
  intro:
    duration: 15
    graphics:
      - type: "title"
        text: "Disaster Response Platform"
        start: 0
        end: 15
        position: "center"
        fontsize: 72
        fontcolor: "white"
        boxcolor: "black@0.7"
        boxborderw: 10
        x: "(w-text_w)/2"
        y: 50
      
      - type: "subtitle"
        text: "Palantir Building Challenge Project"
        start: 2
        end: 13
        position: "center"
        fontsize: 48
        fontcolor: "white"
        boxcolor: "black@0.5"
        boxborderw: 5
        x: "(w-text_w)/2"
        y: 150

  problem:
    duration: 25
    graphics:
      - type: "title"
        text: "Problem Statement"
        start: 0
        end: 25
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "red@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "callout"
        text: "Fragmented Response Systems"
        start: 5
        end: 15
        position: "right"
        fontsize: 36
        fontcolor: "white"
        boxcolor: "red@0.8"
        boxborderw: 5
        x: "w-text_w-50"
        y: 200
      
      - type: "callout"
        text: "Limited Access to Tools"
        start: 15
        end: 25
        position: "left"
        fontsize: 36
        fontcolor: "white"
        boxcolor: "orange@0.8"
        boxborderw: 5
        x: 50
        y: 200

  users:
    duration: 20
    graphics:
      - type: "title"
        text: "Target Users"
        start: 0
        end: 20
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "role"
        text: "Incident Commanders"
        start: 3
        end: 8
        position: "top-left"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: 50
        y: 200
      
      - type: "role"
        text: "Operations Chiefs"
        start: 8
        end: 13
        position: "top-right"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: "w-text_w-300"
        y: 200
      
      - type: "role"
        text: "Field Units"
        start: 13
        end: 18
        position: "bottom-left"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: 50
        y: "h-text_h-100"
      
      - type: "role"
        text: "Dispatchers"
        start: 18
        end: 20
        position: "bottom-right"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: "w-text_w-200"
        y: "h-text_h-100"

  architecture:
    duration: 30
    graphics:
      - type: "title"
        text: "Technical Architecture"
        start: 0
        end: 30
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "component"
        text: "React + Mapbox"
        start: 5
        end: 10
        position: "top-left"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: 50
        y: 300
      
      - type: "component"
        text: "Python/Flask"
        start: 10
        end: 15
        position: "top-right"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: "w-text_w-250"
        y: 300
      
      - type: "component"
        text: "Palantir Foundry"
        start: 15
        end: 20
        position: "center"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 6
        x: "(w-text_w)/2"
        y: "(h-text_h)/2"
      
      - type: "component"
        text: "NOAA/NASA/USGS"
        start: 20
        end: 25
        position: "bottom-left"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: 50
        y: "h-text_h-150"
      
      - type: "component"
        text: "AIP Assistant"
        start: 25
        end: 30
        position: "bottom-right"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "purple@0.8"
        boxborderw: 5
        x: "w-text_w-250"
        y: "h-text_h-150"

  detect:
    duration: 15
    graphics:
      - type: "title"
        text: "Detect & Verify"
        start: 0
        end: 15
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "red@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "alert"
        text: "SATELLITE FIRE DETECTED"
        start: 3
        end: 12
        position: "center"
        fontsize: 48
        fontcolor: "red"
        boxcolor: "yellow@0.9"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: "(h-text_h)/2"
      
      - type: "status"
        text: "Risk Assessment: HIGH"
        start: 8
        end: 15
        position: "bottom"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "red@0.8"
        boxborderw: 5
        x: "(w-text_w)/2"
        y: "h-text_h-50"

  triage:
    duration: 10
    graphics:
      - type: "title"
        text: "Risk Scoring"
        start: 0
        end: 10
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "orange@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "decision"
        text: "EVACUATE"
        start: 3
        end: 10
        position: "center"
        fontsize: 56
        fontcolor: "white"
        boxcolor: "red@0.9"
        boxborderw: 10
        x: "(w-text_w)/2"
        y: "(h-text_h)/2"
      
      - type: "reason"
        text: "Near Critical Infrastructure"
        start: 5
        end: 10
        position: "bottom"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "orange@0.8"
        boxborderw: 5
        x: "(w-text_w)/2"
        y: "h-text_h-50"

  zones:
    duration: 10
    graphics:
      - type: "title"
        text: "Define Evacuation Zones"
        start: 0
        end: 10
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "red@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "tool"
        text: "Drawing Tool Active"
        start: 2
        end: 8
        position: "top-right"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "orange@0.8"
        boxborderw: 5
        x: "w-text_w-200"
        y: 100
      
      - type: "zone"
        text: "Priority Zone Set"
        start: 6
        end: 10
        position: "center"
        fontsize: 40
        fontcolor: "white"
        boxcolor: "red@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: "(h-text_h)/2"

  routes:
    duration: 20
    graphics:
      - type: "title"
        text: "Route Planning"
        start: 0
        end: 20
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "profile"
        text: "Civilian Route"
        start: 3
        end: 8
        position: "top-left"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: 50
        y: 400
      
      - type: "profile"
        text: "EMS Route"
        start: 8
        end: 13
        position: "top-right"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: "w-text_w-200"
        y: 400
      
      - type: "profile"
        text: "Fire Tactical"
        start: 13
        end: 18
        position: "bottom-left"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: 50
        y: "h-text_h-100"
      
      - type: "profile"
        text: "Police Route"
        start: 18
        end: 20
        position: "bottom-right"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: "w-text_w-200"
        y: "h-text_h-100"

  units:
    duration: 10
    graphics:
      - type: "title"
        text: "Unit Assignment"
        start: 0
        end: 10
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "gold@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "unit"
        text: "Engine 1"
        start: 2
        end: 6
        position: "left"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "gold@0.8"
        boxborderw: 5
        x: 50
        y: 300
      
      - type: "unit"
        text: "Medic 2"
        start: 4
        end: 8
        position: "right"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "gold@0.8"
        boxborderw: 5
        x: "w-text_w-150"
        y: 300
      
      - type: "status"
        text: "Building Status: Evacuated"
        start: 6
        end: 10
        position: "bottom"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: "(w-text_w)/2"
        y: "h-text_h-50"

  ai_support:
    duration: 20
    graphics:
      - type: "title"
        text: "AI Decision Support"
        start: 0
        end: 20
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "purple@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "query"
        text: "What if Highway 30 closes?"
        start: 3
        end: 12
        position: "center"
        fontsize: 36
        fontcolor: "white"
        boxcolor: "purple@0.8"
        boxborderw: 5
        x: "(w-text_w)/2"
        y: "(h-text_h)/2-50"
      
      - type: "response"
        text: "Alternative Routes Generated"
        start: 10
        end: 18
        position: "bottom"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: "(w-text_w)/2"
        y: "(h-text_h)/2+50"

  value:
    duration: 30
    graphics:
      - type: "title"
        text: "Value Proposition"
        start: 0
        end: 30
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "benefit"
        text: "Faster Decisions"
        start: 5
        end: 12
        position: "top-left"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: 50
        y: 300
      
      - type: "benefit"
        text: "Reduced Staffing"
        start: 12
        end: 19
        position: "top-right"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: "w-text_w-250"
        y: 300
      
      - type: "benefit"
        text: "Common Operating Picture"
        start: 19
        end: 26
        position: "bottom-left"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: 50
        y: "h-text_h-150"
      
      - type: "benefit"
        text: "Save Lives & Property"
        start: 26
        end: 30
        position: "bottom-right"
        fontsize: 32
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 5
        x: "w-text_w-300"
        y: "h-text_h-150"

  foundry:
    duration: 20
    graphics:
      - type: "title"
        text: "Foundry Integration"
        start: 0
        end: 20
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "feature"
        text: "Data Pipelines"
        start: 3
        end: 8
        position: "top-left"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: 50
        y: 300
      
      - type: "feature"
        text: "Ontology"
        start: 8
        end: 13
        position: "top-right"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: "w-text_w-150"
        y: 300
      
      - type: "feature"
        text: "Context-Aware AI"
        start: 13
        end: 18
        position: "bottom-left"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "purple@0.8"
        boxborderw: 5
        x: 50
        y: "h-text_h-150"
      
      - type: "feature"
        text: "Predictive Analytics"
        start: 18
        end: 20
        position: "bottom-right"
        fontsize: 28
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 5
        x: "w-text_w-300"
        y: "h-text_h-150"

  conclusion:
    duration: 20
    graphics:
      - type: "title"
        text: "Conclusion"
        start: 0
        end: 20
        position: "top"
        fontsize: 60
        fontcolor: "white"
        boxcolor: "green@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: 30
      
      - type: "highlight"
        text: "Real-time Data + AI"
        start: 3
        end: 10
        position: "center"
        fontsize: 44
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: "(h-text_h)/2"
      
      - type: "highlight"
        text: "Streamlined Command"
        start: 10
        end: 17
        position: "center"
        fontsize: 44
        fontcolor: "white"
        boxcolor: "blue@0.8"
        boxborderw: 8
        x: "(w-text_w)/2"
        y: "(h-text_h)/2"
      
      - type: "cta"
        text: "Let's Pilot This Together"
        start: 15
        end: 20
        position: "bottom"
        fontsize: 48
        fontcolor: "white"
        boxcolor: "green@0.9"
        boxborderw: 10
        x: "(w-text_w)/2"
        y: "h-text_h-100"

# Image overlay configuration
image_overlays:
  # Example image overlay configuration
  # - filename: "architecture-diagram.png"
  #   start: 60  # Start time in seconds
  #   end: 90    # End time in seconds
  #   x: 100     # X position on screen
  #   y: 200     # Y position on screen
  #   scale: 0.5 # Scale factor (optional)

# Transition effects configuration
transitions:
  enabled: true
  fade_duration: 1.0  # Duration of fade transitions in seconds
  fade_type: "in_out" # "in", "out", "in_out"

# Global graphics settings
global_settings:
  default_font: "Arial"
  default_fontsize: 32
  default_fontcolor: "white"
  default_boxcolor: "black@0.7"
  default_boxborderw: 5
  safe_margin: 50  # Safe margin from screen edges

