"""Type stubs for palantir.functions."""

from typing import Any, Dict, List, Optional, Union, Callable

def get_function(function_id: str) -> Any: ...
def invoke_function(function_id: str, *args: Any, **kwargs: Any) -> Any: ...

class Function:
    def __init__(self, function_id: str) -> None: ...
    def invoke(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def get_parameters(self) -> List[Dict[str, Any]]: ...
    def get_return_type(self) -> Any: ...
