"""Type stubs for palantir.geocoding."""

from typing import Any, Dict, List, Optional, Union, Tuple

def geocode(address: str) -> Dict[str, Any]: ...
def reverse_geocode(lat: float, lng: float) -> Dict[str, Any]: ...
def batch_geocode(addresses: List[str]) -> List[Dict[str, Any]]: ...
def batch_reverse_geocode(coordinates: List[Tuple[float, float]]) -> List[Dict[str, Any]]: ...

class GeocodingClient:
    def geocode(self, address: str) -> Dict[str, Any]: ...
    def reverse_geocode(self, lat: float, lng: float) -> Dict[str, Any]: ...
    def batch_geocode(self, addresses: List[str]) -> List[Dict[str, Any]]: ...
    def batch_reverse_geocode(self, coordinates: List[Tuple[float, float]]) -> List[Dict[str, Any]]: ...
