"""Type stubs for palantir.ontology."""

from typing import Any, Dict, List, Optional, Union, Callable, TypeVar

T = TypeVar('T')

def Link(property_type: str) -> Any: ...

class PropertyType:
    def __init__(self, primary_key: bool = False, **kwargs: Any) -> None: ...

class ObjectType:
    def __init__(self, api_name: str, **kwargs: Any) -> None: ...

class OntologyObject:
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

def get_ontology() -> Any: ...
def get_object_type(object_type: str) -> Any: ...
def get_property_type(property_type: str) -> Any: ...
