# Disaster Response Dashboard - 7-Minute Technical Deep Dive
# Palantir Building Challenge Submission - Technical Deep Dive

metadata:
  title: "Disaster Response Dashboard - Technical Deep Dive"
  duration: 420  # 7 minutes (420 seconds)
  language: "en-US"
  voice_provider: "elevenlabs"  # openai, elevenlabs, azure, piper
  voice_settings:
    speed: 1.0
    pitch: 0
    volume: 1.0

scenes:
  # Personal Introduction & Persona Setup (0-30s)
  - id: "personal_intro"
    title: "Meet Emergency Manager Sarah Chen"
    duration: 30
    narration: "Hi, I'm Ian Frelinger. I'll walk you through how an incident commander or operations section chief uses our web tool to size up a live situation, pick the right resource, plan access and monitor progress."
    voice: "alloy"  # OpenAI voice
    emphasis: "Incident Commander, Operations Section Chief, web tool, live situation, resource planning"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  # Problem & Outcomes (30-75s)
  - id: "problem_outcomes"
    title: "The Challenge: Seconds Matter in Live Incidents"
    duration: 45
    narration: "In a live incident, seconds matter. The challenge is seeing hazards, exposure and conditions in one place, then turning that into clear assignments. Our goal is faster time-to-decision, safer access to the scene and continuous status you can trust."
    voice: "alloy"
    emphasis: "live incident, seconds matter, hazards, exposure, conditions, time-to-decision, safer access"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  # Data & Architecture (75-135s)
  - id: "data_architecture"
    title: "Data & Architecture: Real-time Integration"
    duration: 60
    narration: "Data streams in from F-I-R-M-S, N-O-A-A, nine one one, population and traffic, and is fused in Palantir Foundry. The backend is Python and Flask, with Celery and WebSockets for real-time updates. The front end is React with Mapbox. The system provides APIs for hazards, risk assessment, route planning, unit management, evacuation tracking and public safety functions."
    voice: "alloy"
    emphasis: "FIRMS, NOAA, 911, population, traffic, Palantir Foundry, Python, Flask, Celery, WebSockets, React, Mapbox"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Live Hazard Map (135-195s)
  - id: "live_hazard_map"
    title: "Live Hazard Map: Situational Awareness"
    duration: 60
    narration: "We operate from the Live Hazard Map. Hazard cells give immediate situational awareness—what's active, where it's clustered and where to focus next."
    voice: "alloy"
    emphasis: "Live Hazard Map, hazard cells, situational awareness, active threats, clustering"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Exposure & Conditions (195-255s)
  - id: "exposure_conditions"
    title: "Exposure & Conditions: Buildings & Weather"
    duration: 60
    narration: "I turn on the buildings and weather layers. Buildings act as a practical proxy for population. Weather shows the conditions that will shape access and operations."
    voice: "alloy"
    emphasis: "Buildings layer, Weather layer, population proxy, conditions, access, operations"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Incident Focus (255-315s)
  - id: "incident_focus"
    title: "Incident Focus: Anchoring the Workflow"
    duration: 60
    narration: "I center the map on a specific hazard. This anchors the workflow to the right location and helps me prioritize the next move."
    voice: "alloy"
    emphasis: "center map, specific hazard, anchor workflow, location, prioritize"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Resource Roster (315-375s)
  - id: "resource_roster"
    title: "Resource Roster: Unit Management"
    duration: 60
    narration: "Next, I open the units panel and select a fire engine from the roster. The roster keeps status and location at a glance so I can match the assignment to the right capability."
    voice: "alloy"
    emphasis: "Units panel, fire engine, roster, status, location, assignment, capability"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Route Planning (375-435s)
  - id: "route_planning"
    title: "Route Planning: Tactical Profiles"
    duration: 60
    narration: "I open the routing panel and choose a fire tactical profile. The system shows the route that matches this profile, including the staging and access points."
    voice: "alloy"
    emphasis: "Routing panel, Fire Tactical profile, route matching, staging, access points"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Route Result (435-495s)
  - id: "route_result"
    title: "Route Result: ETA & Distance Review"
    duration: 60
    narration: "I review the route details—an estimated time of arrival and distance. This tells me how long it will take and which path the unit will follow."
    voice: "alloy"
    emphasis: "route details, estimated time of arrival, distance, path, unit"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Tasking (495-555s)
  - id: "tasking"
    title: "Tasking: Plan to Execution"
    duration: 60
    narration: "With the route validated, I confirm the unit will follow it. The plan moves from planning to execution."
    voice: "alloy"
    emphasis: "route validated, confirm, unit, plan, execution"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # AIP Guidance (555-615s)
  - id: "aip_guidance"
    title: "AIP Decision Support: AI Recommendations"
    duration: 60
    narration: "In A-I-P decision support, I review recommendations and their confidence levels. It's a quick cross-check that our plan aligns with the current risk picture."
    voice: "alloy"
    emphasis: "AIP Decision Support, recommendations, confidence levels, cross-check, plan alignment, risk picture"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  # Ops Status & CTA (615-675s)
  - id: "ops_status_cta"
    title: "Operations Status & Call to Action"
    duration: 60
    narration: "I open the building evacuation tracker to monitor status and progress. From map to assignment to tracking, everything stays connected. If this matches your mission profile, I'd be happy to walk through a personalized scenario next."
    voice: "alloy"
    emphasis: "Building Evacuation Tracker, monitor status, progress, connected workflow, mission profile, personalized scenario"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  # Outro & Conclusion (675-720s)
  - id: "outro_conclusion"
    title: "Outro & Conclusion"
    duration: 45
    narration: "Thank you for joining me on this technical deep dive into our disaster response platform. We've demonstrated how real-time data integration, intelligent routing, and AI-powered decision support can transform emergency response operations. This system represents the future of emergency management—where every second counts and every decision matters. For more information or to schedule a personalized demo, please visit our website or contact our team. Together, we can build a safer, more resilient future."
    voice: "alloy"
    emphasis: "technical deep dive, disaster response platform, real-time data integration, intelligent routing, AI-powered decision support, emergency response operations, emergency management, personalized demo, safer future"
    capture_method: "screenshot"  # Static slide - use screenshot capture

# Capture method configurations
capture_settings:
  screenshot:
    method: "static_slide"
    format: "png"
    resolution: "3840x2160"
    quality: "high"
    delay: 2.0  # seconds to wait before capture
    include_cursor: false
    output_path: "captures/screenshots/"
    
  video:
    method: "dynamic_interaction"
    format: "webm"
    resolution: "3840x2160"
    framerate: 30
    duration: "auto"  # auto-detect based on scene duration
    include_audio: false
    include_cursor: true
    output_path: "captures/videos/"
    compression:
      codec: "vp9"
      quality: "good"
      bitrate: "4000k"

voice_providers:
  openai:
    model: "gpt-4o-mini-tts"
    voice: "alloy"
    speed: 1.0
    api_key_env: "OPENAI_API_KEY"
    
  elevenlabs:
    voice_id: "LIpBYrITLsIquxoXdSkr"  # Cloned voice ID from config
    stability: 0.5
    similarity_boost: 0.75
    api_key_env: "ELEVEN_API_KEY"
    
  azure:
    voice: "en-US-JennyNeural"
    region: "eastus"
    api_key_env: "AZURE_SPEECH_KEY"
    region_env: "AZURE_SPEECH_REGION"
    
  piper:
    voice: "en_US-amy-low.onnx"
    model_path: "./voices/en_US-amy-low.onnx"
    config_path: "./voices/en_US-amy-low.onnx.json"
    speed: 1.0
    noise_scale: 0.667
    length_scale: 1.0
    noise_w: 0.8

audio_settings:
  sample_rate: 44100
  bit_depth: 16
  channels: 1
  format: "wav"
  normalization: "loudness"
  target_lufs: -23.0
  true_peak: -1.0
  
  processing:
    noise_reduction: true
    compression: true
    equalization: true
    reverb: false
    
  output:
    per_scene: "audio/vo/"
    merged: "audio/voiceover.wav"
    subtitles: "subs/vo.srt"

# Timeline alignment notes
timeline_alignment:
  total_duration: 420  # 7 minutes
  scenes_count: 10
  technical_focus: true
  foundry_integration: true
  ai_capabilities: true
  implementation_details: true
  
  # Scene timing alignment with timeline-7min-technical.yaml
  scene_timing:
    personal_intro: "0-20s (A01_personal_intro)"
    user_persona: "20-45s (A02_user_persona)"
    foundry_architecture: "45-105s (B01_foundry_architecture)"
    platform_overview: "105-150s (C01_platform_overview)"
    hazard_management: "150-195s (C02_hazard_management)"
    evacuation_routing: "195-240s (C03_evacuation_routing)"
    ai_decision_support: "240-285s (D01_ai_decision_support)"
    technical_implementation: "285-330s (D02_technical_implementation)"
    integration_scenarios: "330-375s (E01_integration_scenarios)"
    strong_cta: "375-420s (E02_strong_cta)"
