# Disaster Response Dashboard - 4-Minute Video Narration
# Palantir Building Challenge Submission

metadata:
  title: "Disaster Response Dashboard Demo"
  duration: 117
  language: "en-US"
  voice_provider: "elevenlabs"  # openai, elevenlabs, azure, piper
  voice_settings:
    speed: 1.0
    pitch: 0
    volume: 1.0

scenes:
  - id: "intro"
    title: "Dashboard Overview"
    duration: 8
    narration: "When disasters hit, emergency managers are stuck dealing with a mess of disconnected systems and slow responses. Every minute wasted puts lives at risk. The old way takes hours to get organized - but we don't have hours to spare."
    voice: "alloy"  # OpenAI voice
    emphasis: "disasters, mess, slow, lives, hours"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  - id: "hazards"
    title: "Multi-Hazard Map"
    duration: 10
    narration: "We've built one dashboard that brings everyone together - emergency commanders, first responders, and agencies all working from the same page. You can see every threat as it happens. Our map pulls together wildfire, flood, earthquake, and weather data in real-time."
    voice: "alloy"
    emphasis: "one, together, same, threat, pulls"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  - id: "routes"
    title: "Evacuation Routes"
    duration: 12
    narration: "Get safe evacuation routes with just one click. Our AI looks at the terrain, checks for hazards, and monitors traffic to find the safest way out. The routes keep updating as things change - what was safe ten minutes ago might be dangerous now."
    voice: "alloy"
    emphasis: "safe, AI, looks, updating, dangerous"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  - id: "3d-terrain"
    title: "3D Terrain View"
    duration: 10
    narration: "3D terrain view shows you the lay of the land like never before. You can see elevation changes, flood zones, and escape routes that flat maps just can't show. Navigate tricky landscapes with confidence, knowing every hill and obstacle."
    voice: "alloy"
    emphasis: "3D, lay, never, tricky, confidence"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  - id: "evacuation"
    title: "Evacuation Management"
    duration: 12
    narration: "Managing mass evacuations doesn't have to be chaos. Our dashboard keeps track of every vehicle, person, and resource as it moves. Coordinate thousands of people through safe zones while keeping your finger on the pulse of the situation."
    voice: "alloy"
    emphasis: "chaos, keeps, thousands, safe, pulse"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  - id: "ai-support"
    title: "AI Decision Support"
    duration: 15
    narration: "AI spots patterns and gives you real-time advice when you need it most. Make smart decisions even under pressure. Our system learns from every incident, constantly getting better at response strategies and figuring out where to put resources."
    voice: "alloy"
    emphasis: "spots, advice, smart, learns, better"
    capture_method: "video"  # Dynamic interaction - use video capture
    
  - id: "weather"
    title: "Weather Integration"
    duration: 10
    narration: "Real-time weather data from NOAA shows you what's coming, so you can stay ahead of the storm. We connect forecasts with evacuation planning and hazard assessment, so you're not just reacting - you're planning ahead."
    voice: "alloy"
    emphasis: "shows, coming, ahead, connecting, planning"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  - id: "commander"
    title: "Commander View"
    duration: 8
    narration: "Commanders get the big picture with key metrics and resource allocation at a glance. Monitor multiple incidents at once while keeping control of the whole operation. It's like having eyes everywhere without getting overwhelmed."
    voice: "alloy"
    emphasis: "big, key, once, control, everywhere"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  - id: "responder"
    title: "First Responder View"
    duration: 8
    narration: "First responders get the details they need for immediate action - turn-by-turn directions, hazard alerts, and team status. Get what you need when every second counts, without drowning in unnecessary information."
    voice: "alloy"
    emphasis: "details, immediate, second, drowning, unnecessary"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  - id: "public"
    title: "Public Information"
    duration: 8
    narration: "Keep people in the loop with real-time updates. Clear communication saves lives and keeps panic at bay. Give folks accurate, timely information through multiple channels so everyone stays safe and informed."
    voice: "alloy"
    emphasis: "loop, saves, panic, accurate, informed"
    capture_method: "screenshot"  # Static slide - use screenshot capture
    
  - id: "outro"
    title: "Call to Action"
    duration: 6
    narration: "Our system dramatically increases response throughput and allows for greater effectiveness of emergency responses. Transform your emergency management today. When minutes matter, every second you save could mean the difference between life and death."
    voice: "alloy"
    emphasis: "dramatically, increases, effectiveness, transform, difference"
    capture_method: "screenshot"  # Static slide - use screenshot capture

# Capture method configurations
capture_settings:
  screenshot:
    method: "static_slide"
    format: "png"
    resolution: "1920x1080"
    quality: "high"
    delay: 2.0  # seconds to wait before capture
    include_cursor: false
    output_path: "captures/screenshots/"
    
  video:
    method: "dynamic_interaction"
    format: "webm"
    resolution: "1920x1080"
    framerate: 30
    duration: "auto"  # auto-detect based on scene duration
    include_audio: false
    include_cursor: true
    output_path: "captures/videos/"
    compression:
      codec: "vp9"
      quality: "good"
      bitrate: "2000k"

voice_providers:
  openai:
    model: "gpt-4o-mini-tts"
    voice: "alloy"
    speed: 1.0
    api_key_env: "OPENAI_API_KEY"
    
  elevenlabs:
    voice_id: "LIpBYrITLsIquxoXdSkr"  # Cloned voice ID from config
    stability: 0.5
    similarity_boost: 0.75
    api_key_env: "ELEVEN_API_KEY"
    
  azure:
    voice: "en-US-JennyNeural"
    region: "eastus"
    api_key_env: "AZURE_SPEECH_KEY"
    region_env: "AZURE_SPEECH_REGION"
    
  piper:
    voice: "en_US-amy-low.onnx"
    model_path: "./voices/en_US-amy-low.onnx"
    config_path: "./voices/en_US-amy-low.onnx.json"
    speed: 1.0
    noise_scale: 0.667
    length_scale: 1.0
    noise_w: 0.8

audio_settings:
  sample_rate: 44100
  bit_depth: 16
  channels: 1
  format: "wav"
  normalization: "loudness"
  target_lufs: -23.0
  true_peak: -1.0
  
  processing:
    noise_reduction: true
    compression: true
    equalization: true
    reverb: false
    
  output:
    per_scene: "audio/vo/"
    merged: "audio/voiceover.wav"
    subtitles: "subs/vo.srt"
