timeline:
  duration: 420  # Extended from 340 to accommodate new segments
  fps: 30
  resolution: [1920, 1080]
  tracks:
    video:
      # NEW: Personal Introduction (I001 fix)
      - { name: "A01_personal_intro",    source: "captures/personal_intro.webm",    start: 0,   duration: 15, transitions: { in: fade, out: fade } }
      
      # NEW: User Persona Definition (I002 fix)  
      - { name: "A02_user_persona",      source: "captures/user_persona.webm",      start: 15,  duration: 20, transitions: { in: fade, out: fade } }
      
      # Original intro now starts at 35s
      - { name: "B01_intro",            source: "captures/intro.webm",            start: 35,  duration: 30, transitions: { in: fade, out: fade } }
      - { name: "B02_roles",            source: "captures/roles.webm",            start: 65,  duration: 30, transitions: { in: fade, out: fade } }
      
      # EXTENDED: API Architecture with Foundry emphasis (I003 fix)
      - { name: "B03_api",              source: "captures/api_overview.webm",     start: 95,  duration: 50, transitions: { in: fade, out: fade } }
      
      # EXTENDED: Map interaction with action demonstration (I004 fix)
      - { name: "B04_map",              source: "captures/map_triage.webm",       start: 145, duration: 50, transitions: { in: fade, out: fade } }
      
      - { name: "B05_zones",            source: "captures/zones.webm",            start: 195, duration: 40, transitions: { in: fade, out: fade } }
      - { name: "B06_route",            source: "captures/route_concept.webm",    start: 235, duration: 40, transitions: { in: fade, out: fade } }
      - { name: "B07_ai",               source: "captures/ai_concept.webm",       start: 275, duration: 30, transitions: { in: fade, out: fade } }
      - { name: "B08_tech",             source: "captures/tech_deep.webm",        start: 305, duration: 40, transitions: { in: fade, out: fade } }
      - { name: "B09_impact",           source: "captures/impact.webm",           start: 345, duration: 30, transitions: { in: fade, out: fade } }
      
      # EXTENDED: Stronger conclusion with CTA (I005 fix)
      - { name: "B10_conclusion",       source: "captures/conclusion.webm",       start: 375, duration: 45, transitions: { in: fade, out: fade } }

    audio:
      voiceover:
        source: "audio/voiceover.wav"
        start: 0
        duration: 420
        volume: 1.0
        ducking: true
        
      music:
        source: "audio/music.wav"
        start: 0
        duration: 420
        volume: 0.3
        fade:
          in: 2
          out: 3
        
      effects:
        - name: "transition-sound"
          source: "audio/transition.wav"
          start: 15
          duration: 0.5
          volume: 0.4
        - name: "highlight-sound"
          source: "audio/highlight.wav"
          start: 275
          duration: 0.3
          volume: 0.6
    
    graphics:
      lower-thirds:
        # NEW: Personal Introduction
        - text: "Ian Frelinger - Personal Introduction"
          start: 0
          duration: 15
          position: "center"
          style: "personal"
        
        # NEW: User Persona Definition
        - text: "Target Users: Incident Commanders & Emergency Planners"
          start: 15
          duration: 20
          position: "center"
          style: "persona"
        
        # Original content with adjusted timing
        - text: "Disaster Response Platform"
          start: 35
          duration: 30
          position: "center"
          style: "title"
        
        - text: "Incident Commander · Planner · Dispatcher"
          start: 65
          duration: 30
          position: "bottom-left"
          style: "roles"
        
        # EXTENDED: API with Foundry emphasis
        - text: "Foundry Platform: API Architecture & Data Flow"
          start: 95
          duration: 50
          position: "bottom-center"
          style: "tech"
        
        # EXTENDED: Map with action demonstration
        - text: "Live Hazard Detection & User Actions"
          start: 145
          duration: 50
          position: "bottom-right"
          style: "hazard"
        
        - text: "Zone Management & Building Status"
          start: 195
          duration: 40
          position: "bottom-left"
          style: "zones"
        
        - text: "A-Star Route Optimization"
          start: 235
          duration: 40
          position: "bottom-center"
          style: "routes"
        
        - text: "AI Decision Support"
          start: 275
          duration: 30
          position: "center"
          style: "ai"
        
        - text: "Technical Deep Dive"
          start: 305
          duration: 40
          position: "bottom-right"
          style: "tech"
        
        - text: "Impact & Value Proposition"
          start: 345
          duration: 30
          position: "center"
          style: "impact"
        
        # EXTENDED: Stronger conclusion
        - text: "Ian Frelinger · Let's Discuss Your Emergency Management Needs"
          start: 375
          duration: 45
          position: "bottom-center"
          style: "contact"
      
      # NEW: Action demonstration overlays (I004 fix)
      overlays:
        - id: "intro_candidate"
          type: "text_card"
          start: 0
          duration: 15
          position: "center"
          style: "personal_intro"
          content: "Hi, I'm Ian Frelinger. I'm building this disaster response platform because I believe emergency managers deserve better tools when lives are at stake."
        
        - id: "user_persona_card"
          type: "info_card"
          start: 15
          duration: 20
          position: "center"
          style: "persona_definition"
          content: "This platform serves Incident Commanders, Emergency Planners, and Dispatchers who need real-time coordination during disasters."
        
        - id: "foundry_architecture"
          type: "tech_diagram"
          start: 95
          duration: 50
          position: "right"
          style: "architecture"
          content: "Foundry enables real-time data streaming, ontology management, and action workflows for emergency response."
        
        - id: "action_card"
          type: "interaction_demo"
          start: 145
          duration: 50
          position: "overlay"
          style: "action_demonstration"
          content: "Click on hazards to see risk analysis, population at risk, and recommended actions - all powered by Foundry's ontology."
        
        - id: "strong_cta"
          type: "call_to_action"
          start: 375
          duration: 45
          position: "center"
          style: "engagement"
          content: "I'd love to show you a longer demo and discuss how this platform can transform your emergency management operations."
      
      captions:
        source: "subs/vo.srt"
        style: "modern"
        position: "bottom-center"
        background: "semi-transparent"
        font: "Arial"
        size: 24
        color: "white"
        outline: "black"
    
    effects:
      color-grading:
        lut: "luts/emergency-response.cube"
        intensity: 0.7
        
      stabilization:
        enabled: true
        smoothing: 0.3
        
      enhancement:
        sharpness: 1.2
        contrast: 1.1
        saturation: 1.05
        
  output:
    rough-cut: "out/roughcut_fixed.mp4"
    final: "out/final_fixed.mp4"
    edl: "out/final_fixed.edl"
    premiere: "out/final_fixed.xml"
    metadata:
      title: "Disaster Response Platform - Enhanced Demo with Personal Introduction"
      description: "Personal introduction and extended technical demo showing Foundry-powered emergency coordination platform with AI decision support"
      author: "Ian Frelinger"
      copyright: "2024 Ian Frelinger"
      keywords: ["emergency", "disaster", "response", "platform", "AI", "evacuation", "palantir", "foundry", "personal", "demo"]
