timeline:
  duration: 127  # Total duration in seconds (2:07)
  fps: 30
  resolution: [3840, 2160]
  
  tracks:
    video:
      - name: "introduction"
        source: "captures/intro.webm"
        start: 0
        duration: 10
        transitions:
          in: "fade"
          out: "crossfade"
        narration: "Hi, I'm Ian Frelinger, and welcome to my Palantir Building Challenge submission. I've built a prototype of a disaster-response dashboard that helps coordinate emergency operations when every second counts."
        visual: "abstract_swirling_artwork"
        graphics:
          - type: "intro_template"
            title: "Disaster Response Platform"
            subtitle: "Palantir Building Challenge Project"
            colors: "emergency_response_blue"
            transition: "fade=t=in:st=0:d=1"
      
      - name: "problem_statement"
        source: "captures/hazards.webm"
        start: 10
        duration: 15
        transitions:
          in: "crossfade"
          out: "slide-left"
        narration: "Emergency responders often juggle radios, maps and spreadsheets. Traditional common operating pictures can overwhelm them with information, and front-line teams rarely have access to the high-level tools reserved for Incident Commanders. This project aims to unify critical data in one place without replacing human judgment."
        visual: "hazard_detection_map"
        graphics:
          - type: "callout_alert"
            text: "Fragmented systems slow response"
            animation: "bounce"
          - type: "callout_info"
            text: "Data overload, Manual fusion, Limited access"
            position: "slide-right"
            colors: "blue"
      
      - name: "user_persona"
        source: "captures/commander.webm"
        start: 25
        duration: 10
        transitions:
          in: "slide-left"
          out: "fade"
        narration: "This dashboard is built for Incident Commanders, Operations and Planning chiefs, dispatchers and front-line responders. We keep the Incident Commander at the top of the chain of command but give every role the same real-time situational awareness."
        visual: "vector_silhouettes"
        graphics:
          - type: "label_role"
            roles: ["Commander", "Planner", "Responder"]
            animation: "fade-in"
          - type: "lower_third_basic"
            name: "Ian Frelinger"
            title: "Developer & Presenter"
      
      - name: "technical_architecture"
        source: "captures/ai-support.webm"
        start: 35
        duration: 15
        transitions:
          in: "fade"
          out: "fade"
        narration: "The front end uses React and Mapbox to deliver a responsive, 3-D map. The backend is Python/Flask with WebSockets for live updates. We ingest satellite, weather and population data, fuse it in Foundry, and expose it through an API. This simplified data-flow diagram shows the path from ingestion through hazard processing into the map."
        visual: "api_data_flow_diagram"
        graphics:
          - type: "technical_template"
            diagram: "api_data_flow"
          - type: "label_component"
            components: ["Ingestion", "Processing", "Map"]
            animation: "fade-in"
      
      - name: "commander_dashboard"
        source: "captures/evacuation.webm"
        start: 50
        duration: 20
        transitions:
          in: "slide-down"
          out: "slide-right"
        narration: "Here's the Commander Dashboard, which summarises our zones, populations and building counts. Zone A is Immediate, Zone B is Warning, and Zone C is Standby. We can quickly see how many buildings have been evacuated, the total population at risk and any special-needs residents."
        visual: "asset_management_status_view"
        graphics:
          - type: "label_component"
            zones: ["Zone A: Immediate", "Zone B: Warning", "Zone C: Standby"]
            animation: "sequential-fade"
          - type: "label_status"
            text: "Evacuated: 1 of 3 buildings"
            position: "bottom"
      
      - name: "live_map_hazard"
        source: "captures/hazards.webm"
        start: 70
        duration: 20
        transitions:
          in: "slide-right"
          out: "crossfade"
        narration: "On the Live Map, hazards appear as red clusters over the city. We can toggle layers for hazards, routes, units and evacuation zones to focus on what matters. This view updates in real time as new detections come in."
        visual: "hazard_detection_map"
        graphics:
          - type: "callout_info"
            text: "Hazards, Routes, Units, Evac Zones"
            position: "vertical"
            animation: "scale-in"
          - type: "zoom_effect"
            target: "hazard_cluster"
            animation: "scale"
          - type: "label_status"
            text: "3 hazards active"
            position: "top"
      
      - name: "simplified_flow"
        source: "captures/3d-terrain.webm"
        start: 90
        duration: 15
        transitions:
          in: "crossfade"
          out: "fade"
        narration: "Because the current UI is a work in progress, today's demo focuses on the dashboard and live hazard view. Future versions will include zone drawing, hazard-aware routing, unit assignment and AI recommendations. For now, this prototype proves that we can unify core data sources and present them clearly to the Incident Commander and the team."
        visual: "operational_overview_diagram"
        graphics:
          - type: "callout_info"
            text: "Coming soon: Zones, Routes, AI & Units"
            animation: "slide-up"
            position: "bottom"
          - type: "graphics_fade"
            effect: "fade"
      
      - name: "conclusion"
        source: "captures/outro.webm"
        start: 105
        duration: 22
        transitions:
          in: "fade"
          out: "fade"
        narration: "In summary, this prototype shows that real-time data fusion and a clean interface can accelerate disaster response while keeping the Incident Commander firmly in charge. I'm excited to expand this into a full system—with zones, routing and AI—and would love to explore pilots or collaborations."
        visual: "sunrise_artwork"
        graphics:
          - type: "title_small"
            text: "Conclusion & Next Steps"
            animation: "scale-in"
            position: "top"
          - type: "lower_third"
            text: "Contact Information & Call to Action"
            duration: 5
            animation: "fade-in"
    
    audio:
      voiceover:
        source: "audio/voiceover.wav"
        start: 0
        duration: 127
        volume: 1.0
        ducking: true
        
      music:
        source: "audio/music.wav"
        start: 0
        duration: 127
        volume: 0.3
        fade:
          in: 2
          out: 3
        
      effects:
        - name: "transition-sound"
          source: "audio/transition.wav"
          start: 10
          duration: 0.5
          volume: 0.4
        - name: "highlight-sound"
          source: "audio/highlight.wav"
          start: 50
          duration: 0.3
          volume: 0.6
    
    graphics:
      lower-thirds:
        - text: "Disaster Response Platform"
          start: 0
          duration: 10
          position: "center"
          style: "emergency-blue"
        
        - text: "Emergency Response Challenges"
          start: 10
          duration: 15
          position: "bottom-left"
          style: "alert-red"
        
        - text: "Target Users & Roles"
          start: 25
          duration: 10
          position: "bottom-center"
          style: "role-gold"
        
        - text: "Technical Architecture"
          start: 35
          duration: 15
          position: "top-right"
          style: "tech-blue"
        
        - text: "Commander Dashboard"
          start: 50
          duration: 20
          position: "bottom-left"
          style: "command-gold"
        
        - text: "Live Map & Hazards"
          start: 70
          duration: 20
          position: "top-center"
          style: "hazard-red"
        
        - text: "Future Roadmap"
          start: 90
          duration: 15
          position: "bottom-right"
          style: "future-green"
        
        - text: "Conclusion & Next Steps"
          start: 105
          duration: 22
          position: "center"
          style: "conclusion-blue"
      
      captions:
        source: "subs/vo.srt"
        style: "modern"
        position: "bottom-center"
        background: "semi-transparent"
        font: "Arial"
        size: 24
        color: "white"
        outline: "black"
    
    effects:
      color-grading:
        lut: "luts/emergency-response.cube"
        intensity: 0.7
        
      stabilization:
        enabled: true
        smoothing: 0.3
        
      enhancement:
        sharpness: 1.2
        contrast: 1.1
        saturation: 1.05
        
  output:
    rough-cut: "out/roughcut-timeline-3.mp4"
    final: "out/final-timeline-3.mp4"
    edl: "out/final-timeline-3.edl"
    premiere: "out/premiere-timeline-3.xml"
    metadata:
      title: "Disaster Response Dashboard - Timeline 3 Demo"
      description: "Palantir Building Challenge submission showcasing real-time emergency management platform"
      author: "Ian Frelinger"
      copyright: "2024 Ian Frelinger"
      keywords: ["emergency", "disaster", "response", "dashboard", "palantir", "challenge"]
