"""Type stubs for transforms.routing.route_optimizer."""

from typing import Any, Dict, List, Optional, Union, Tuple

def optimize_route(waypoints: List[Tuple[float, float]], **kwargs: Any) -> Any: ...
def calculate_route_distance(route: Any) -> float: ...
def calculate_route_time(route: Any) -> float: ...

class RouteOptimizer:
    def __init__(self) -> None: ...
    def optimize(self, waypoints: List[Tuple[float, float]], **kwargs: Any) -> Any: ...
    def calculate_distance(self, route: Any) -> float: ...
    def calculate_time(self, route: Any) -> float: ...
